FROM python:3.11-slim

WORKDIR /app

# Instalar dependencias del sistema mínimas
RUN apt-get update && apt-get install -y \
    build-essential wget git ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Instalar dependencias Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el servidor Flask y los modelos
COPY server.py /app/server.py
COPY model /model

EXPOSE 2700

ENV TZ=Europe/Madrid

CMD ["python", "server.py"]
