FROM python:3.11-slim

# Evitar buffering de logs
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Código
COPY . .

# Entrypoint
CMD ["python", "main.py"]
