FROM python:3.10-slim

# Evita buffers de salida en contenedores
ENV PYTHONUNBUFFERED=1

# Instalamos dependencias del sistema
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copiamos los ficheros
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py entrypoint.sh ./
RUN chmod +x /app/entrypoint.sh

# Monta el modelo local en /models (persistente o compartido)
VOLUME ["/models"]

ENTRYPOINT ["/app/entrypoint.sh"]
