# Imagen base ligera de Python
FROM python:3.11-slim

# Variables de entorno de Python
ENV PYTHONUNBUFFERED=1

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar requirements y luego instalar (caché eficiente)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código del listener
COPY main-listener.py .

# Comando de ejecución
CMD ["python", "main-listener.py"]
